# Generated by Django 4.2.4 on 2023-09-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_change_user_is_active', 'Can change user is active')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
