# Generated by Django 4.2.4 on 2023-09-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='MailingLog',
        ),
    ]
