# Generated by Django 4.2.4 on 2023-09-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
    ]
